<main>
<h1>Loguear Usuario </h1>
 <form class="fom_login" action="?action=loguear" method="POST">
   <fieldset>
  <legend>Datos básicos</legend>
  <label for="nombre">Usuario</label> <br/>
  <input type="text" name="user" class="item_requerid" size="20" maxlength="25"  placeholder="Miguel" />
  <br/>
  <label for="contraseña">Contraseña</label> <br/>
  <input type="text" name="passwd" class="item_requerid" size="20" maxlength="25"   placeholder="Cervantes" /> <br/>
  </fieldset>
  <input type="submit" value="Enviar">
  <input type="reset" value="Deshacer">       
 </form>
 </main>
