<main>
<section id="blog">
				<h1>Últimos artículos</h1>
				
				<article>
					<h2>Llega a las tiendas el iPhone 6</h2>
					<img src="./img/iphone.jpg" class="imgblogmini" />
					<p>Los compradores del iPhone 6 han descubierto una peculiaridad inesperada en sus nuevos teléfonos:
					se doblan cuando se colocan en los bolsillos traseros del pantalón, algo que también sucede con otros dispositivos inteligentes.
					El 'bendgate' (de "bend", doblar), que es el nombre con el que este asunto ha sido bautizado en medios sociales y webs,
					recuerda al 'antenagate' de 2010, que hacía referencia al diseño de la antena del iPhone 4 que provocaba que las llamadas se interrumpieran. La situación podría ser particularmente preocupante para aquéllos que usan pantalones ajustados, de acuerdo con las informaciones de usuarios que circulan por Facebook y Twitter... </p>
					<div class="botonleermas">
						<a href="?blog&num=1">leer más...</a>
					</div>
				</article>
				
				<article>
					<h2>Viajes a la India por menos de 600€</h2>
					<img src="./img/tajmahal.jpg" class="imgblogmini" />
					<p>La India puede ser algo desconcertante en su primera visita. La forma de vida y cultura es totalmente diferente a Occidente.
					Hemos hecho una lista con recomendaciones con cosas que hacer y cosas que no hacer para tener un agradable viaje en India.
					Para su estancia en India necesita Visado, sin ello no puede entrar a India. La mayoría de extranjeros necesitan visado,
					consulte con su agencia antes de realizar el viaje, le podrán informar de cómo hacerlo. Es recomendable hacer un seguro de viaje para su estancia (que cubra perdida de viaje, robos y seguro medico). Si viajas por libre, lleva los mapas apropiados para encontrar los lugares que quieres visitar, en India no suelen haber indicaciones y letreros. Intente buscar de día, evite la noche.</p>
					<div class="botonleermas">
						<a href="?blog&num=2">leer más...</a>
					</div>
				</article>
				
			</section>
			
			<section id="presentacion">
				<h1>Presentación</h1>
				<img src="./img/manos.jpg" width="150" />
				<p>El nuevo siglo es testigo de las  primeras experiencias digitales de ACCE.
				La primera web, muy sencilla, es sustituida  en 2003 por www.acce.org, el portal de la organización de consumidores y usuarios,
				que a lo largo de sus primeros 10 años ha ido ganando en contenido, información y usabilidad para ofrecer respuestas a quienes
				se acercan a ella, así como servicios exclusivos para los socios. Los socios son la razón de ser de ACCE, con sus aportaciones
				hacen posible nuestra tarea, y la organización de consumidores y usuarios busca responder a sus necesidades: a la información
				de calidad de las publicaciones de ACCE se suman una atención personalizada y especializada a través del servicio de asesoría,
				herramientas online, ventajas especiales conseguidas mediante acuerdos exclusivos…</p>
			</section>
			
			<section id="opiniones">
				<h1>Últimas opiniones</h1>
				<div class="opinion">
					<img src="./img/zalando.jpg" class="imgopinion" />
					<div class="cuerpo-opinion">
						<h2>"Un servicio inmejorable"</h2>
						<p class="valoracion-usuario">
						<meter min="0" max="10" low="4" high="8" optimum="10" value="8.5">A+</meter>
						Lucía, Zaragoza
						</p>
						<p>Es facilísimo navegar por la página. Está todo catalogado por secciones para poder encontrar la que más nos convenga,
						y como siempre en estos casos, también dispondremos de un buscador para encontrar directamente lo que queramos. Una vez elegida una categoría, hay subcategorías a elegir que resultan muy útiles. Yo siempre suelo pasarme por la sección de zapatos que es lo que ...</p>
						<div class="botonleermas">
							<a href="?blog&num=3">leer opinión...</a>
						</div>
					</div>
				</div>
			</section>
</main>